### ISSUE TITLE
lwip

### ISSUE THREAD

**Issue by xzfd1010** [Tencent/tmt-workflow#112]
解决node-sass的问题之后，又报错lwip_image不能用。
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/lwip_image'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/nick/front-end/imooc/tmt-workflow/node_modules/node-lwip/lib/Image.js:3:22
    at Object.<anonymous> (/Users/nick/front-end/imooc/tmt-workflow/node_modules/node-lwip/lib/Image.js:16:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

能不能告知哪一个服务用到了这个插件，以便关闭相关的服务，或者说明此workflow能够配置成功时需要的node及npm环境。

**Comment by yuwuxing** [comment]
gulp-tmtsprite 用到了这个模块，最近我也是发现这个问题，把node 切换到6.2.0版本可以安装 6.11.0就安装失败

**Comment by hzlzh** [comment]
建议先不要升级太高的 node 版本，比如我现在项目稳定在使用 5.10.0 运行整套流程，配合 https://github.com/tj/n 切换很方便
```
➜  ~ node -v
v5.10.0
➜  ~ npm -v
3.8.3
```

**Comment by zhengjingfa** [comment]
7.10.0版本的node就会出现这些问题

**Comment by xzfd1010** [comment]
@zhengjingfa 已经按照 @hzlzh 的配置，把node换成了5.10.0版本的，终于跑起来了。

**Comment by hzlzh** [comment]
@zhengjingfa 如果只是运行工作流，建议不要升那么高。
