### ISSUE TITLE
执行任务报错

### ISSUE THREAD

**Issue by BarryZhan** [Tencent/tmt-workflow#119]
```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/barry/works/yingda/xilongfx/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:
	/Users/barry/works/yingda/xilongfx/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __TEXT extends to 1212416 which is past end of file 85528
	/Users/barry/works/yingda/xilongfx/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __TEXT extends to 1212416 which is past end of file 85528
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/barry/works/yingda/xilongfx/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:19:10)
    at Object.<anonymous> (/Users/barry/works/yingda/xilongfx/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
```
重装了好几遍node-sass

**Comment by hzlzh** [comment]
试一下 node -v 5.10.0

**Comment by BarryZhan** [comment]
@hzlzh 这个问题我已经解决了，我的解决方案是 `npm rebuild node-sass`。后面还继续报了几个类似这样的错误，然后一个一个的 rebuild 就好了。

**Comment by hzlzh** [comment]
@BarryZhan 请问你用的 npm 还是 cnpm，有的时候遇到代理会有问题

**Comment by BarryZhan** [comment]
@hzlzh npm 和 yarn 都试了

**Comment by hzlzh** [comment]
那很可能是代理问题了，我也遇到过这个报错，后来挂了稳定的代理就可以很通畅的拉取依赖了
