### ISSUE TITLE
build-dist reversion 报错

### ISSUE THREAD

**Issue by hulei2014** [Tencent/tmt-workflow#127]
[10:51:13] 'reversion' errored after 195 ms
[10:51:13] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (F:\workspace\tmt-workflow\node_modules\vinyl-fs\lib\dest\prepare.js:16:17)
    at DestroyableTransform.Transform._read (F:\workspace\tmt-workflow\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (F:\workspace\tmt-workflow\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (F:\workspace\tmt-workflow\node_modules\readable-stream\lib\_stream_writable.js:418:64)
    at writeOrBuffer (F:\workspace\tmt-workflow\node_modules\readable-stream\lib\_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (F:\workspace\tmt-workflow\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Pumpify.Duplexify._write (F:\workspace\tmt-workflow\node_modules\duplexify\index.js:214:22)
    at doWrite (F:\workspace\tmt-workflow\node_modules\readable-stream\lib\_stream_writable.js:418:64)
    at writeOrBuffer (F:\workspace\tmt-workflow\node_modules\readable-stream\lib\_stream_writable.js:407:5)
    at Pumpify.Writable.write (F:\workspace\tmt-workflow\node_modules\readable-stream\lib\_stream_writable.js:334:11)
[10:51:13] 'build_dist' errored after 12 s

build-dev 正常，build-dist 打包在 reversion 阶段报错，求解！

**Comment by hzlzh** [comment]
尝试重新 npm install 一下试试。
