### ISSUE TITLE
执行 gulp build_dist 报错

### ISSUE THREAD

**Issue by JChehe** [Tencent/tmt-workflow#69]
K:\tmt-workflow\project>gulp build_dist
[16:06:38] Using gulpfile K:\tmt-workflow\project\gulpfile.js
[16:06:38] Starting 'build_dist'...
[16:06:38] Starting 'delDist'...
[16:06:38] Finished 'delDist' after 6.16 ms
[16:06:38] Starting 'compileLess'...
[16:06:38] Starting 'compileSass'...
[16:06:38] Starting 'imageminImg'...
[16:06:38] Starting 'copyMedia'...
[16:06:38] Starting 'compileJs'...
[16:06:38] Finished 'compileSass' after 175 ms
[16:06:38] 'imageminImg' errored after 242 ms
[16:06:38] Error in plugin 'gulp-imagemin:'
Message:
    spawn K:\tmt-workflow\node_modules\jpegtran-bin\vendor\jpegtran.exe ENOENT
Details:
    code: ENOENT
    errno: ENOENT
    syscall: spawn K:\tmt-workflow\node_modules\jpegtran-bin\vendor\jpegtran.exe
    path: K:\tmt-workflow\node_modules\jpegtran-bin\vendor\jpegtran.exe
    spawnargs: -copy,none,-optimize
    fileName: K:\tmt-workflow\project\src\img\front.jpg
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
[16:06:38] 'build_dist' errored after 257 ms
[16:06:38] The following tasks did not complete: compileLess, copyMedia, compileJs
[16:06:38] Did you forget to signal async completion?

**Comment by littledu** [comment]
图片模块没安装好，重新执行一下：
```
npm install gulp-imagemin
```

**Comment by JChehe** [comment]
```
K:\tmt-workflow\project>gulp build_dist
[17:11:08] Using gulpfile K:\tmt-workflow\project\gulpfile.js
[17:11:08] Starting 'build_dist'...
[17:11:08] Starting 'delDist'...
[17:11:08] Finished 'delDist' after 5.37 ms
[17:11:08] Starting 'compileLess'...
[17:11:08] Starting 'compileSass'...
[17:11:08] Starting 'imageminImg'...
[17:11:08] Starting 'copyMedia'...
[17:11:08] Starting 'compileJs'...
[17:11:08] Finished 'compileSass' after 166 ms
[17:11:08] Finished 'copyMedia' after 168 ms
[BABEL] Note: The code generator has deoptimised the styling of "K:/tmt-workflow/project/src/js/base64.js" as it exceeds the max of "100KB".
[17:11:14] Finished 'compileLess' after 6.65 s
[17:11:14] 'imageminImg' errored after 6.78 s
[17:11:14] Error: write EPIPE
    at exports._errnoException (util.js:856:11)
    at Socket._writeGeneric (net.js:676:26)
    at Socket._write (net.js:695:8)
    at doWrite (_stream_writable.js:293:12)
    at writeOrBuffer (_stream_writable.js:279:5)
    at Socket.Writable.write (_stream_writable.js:208:11)
    at Socket.write (net.js:619:40)
    at Socket.Writable.end (_stream_writable.js:434:10)
    at Socket.end (net.js:401:31)
    at Through2._transform (K:\tmt-workflow\node_modules\imagemin-pngquant\index.js:92:12)
[17:11:15] 'build_dist' errored after 6.79 s
[17:11:15] The following tasks did not complete: compileJs
[17:11:15] Did you forget to signal async completion?
```
还是不行

**Comment by littledu** [comment]
你第一个错误重装后就解决了，然后出现第二个错误，之前有朋友反馈类似的报错，都是相应的图片模块没有成功安装，你现在报的是 `imagemin-pngquant` 的错，所以，我还是建议你再重新安装一下：

```
npm install imagemin-pngquant
```

**Comment by luxiaowu** [comment]
D:\ceshi\dingtalk>gulp build_dev
module.js:327
    throw err;
    ^

Error: Cannot find module 'array-uniq'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\ceshi\node_modules\del\node_modules\globby\node_modules\array-union\index.js:2:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by littledu** [comment]
模块没安装全，如果网络允许的话，用npm，如果一定要cnpm的话，可以尝试这样：
1 手动删除整个node_module目录
2 在项目目录下执行 npm cache clean
3 重新 cnpm install

**Comment by hzlzh** [comment]
node 版本是多少，尝试 v5.10.0试试
